OnlyZombieSpawn: true
ZombieCanBreakBlocks: true
LessZombieSpawn: false
ZombieBurn: false

WorkInWorlds:
  - world

Messages:
  ExceptionMessage: '[ZombieApocalypse] Exception: '
  OnEnable: '[ZombieApocalypse] Plugin is started.'
  OnDisable: '[ZombieApocalypse] Plugin is stopped.'

# 0 - can't break, 1 - highest chance to break
SkipAndSetTenForAll: false
ChanceToBreakBlock:
  - ACACIA_BUTTON 10
  - ACACIA_DOOR 10
  - ACACIA_FENCE 10
  - ACACIA_FENCE_GATE 10
  - ACACIA_LEAVES 10
  - ACACIA_LOG 10
  - ACACIA_PLANKS 10
  - ACACIA_PRESSURE_PLATE 10
  - ACACIA_SAPLING 10
  - ACACIA_SIGN 10
  - ACACIA_SLAB 10
  - ACACIA_STAIRS 10
  - ACACIA_TRAPDOOR 10
  - ACACIA_WALL_SIGN 10
  - ACACIA_WOOD 10
  - ACTIVATOR_RAIL 10
  - AIR 0
  - ALLIUM 10
  - ANCIENT_DEBRIS 10
  - ANDESITE 10
  - ANDESITE_SLAB 10
  - ANDESITE_STAIRS 10
  - ANDESITE_WALL 10
  - ANVIL 10
  - ATTACHED_MELON_STEM 10
  - ATTACHED_PUMPKIN_STEM 10
  - AZURE_BLUET 10
  - BAMBOO 10
  - BAMBOO_SAPLING 10
  - BARREL 10
  - BARRIER 10
  - BASALT 10
  - BEACON 10
  - BEDROCK 0
  - BEEHIVE 10
  - BEETROOTS 10
  - BEE_NEST 10
  - BELL 10
  - BIRCH_BUTTON 10
  - BIRCH_DOOR 10
  - BIRCH_FENCE 10
  - BIRCH_FENCE_GATE 10
  - BIRCH_LEAVES 10
  - BIRCH_LOG 10
  - BIRCH_PLANKS 10
  - BIRCH_PRESSURE_PLATE 10
  - BIRCH_SAPLING 10
  - BIRCH_SIGN 10
  - BIRCH_SLAB 10
  - BIRCH_STAIRS 10
  - BIRCH_TRAPDOOR 10
  - BIRCH_WALL_SIGN 10
  - BIRCH_WOOD 10
  - BLACKSTONE 10
  - BLACKSTONE_SLAB 10
  - BLACKSTONE_STAIRS 10
  - BLACKSTONE_WALL 10
  - BLACK_BANNER 10
  - BLACK_BED 10
  - BLACK_CARPET 10
  - BLACK_CONCRETE 10
  - BLACK_CONCRETE_POWDER 10
  - BLACK_GLAZED_TERRACOTTA 10
  - BLACK_SHULKER_BOX 10
  - BLACK_STAINED_GLASS 10
  - BLACK_STAINED_GLASS_PANE 10
  - BLACK_TERRACOTTA 10
  - BLACK_WALL_BANNER 10
  - BLACK_WOOL 10
  - BLAST_FURNACE 10
  - BLUE_BANNER 10
  - BLUE_BED 10
  - BLUE_CARPET 10
  - BLUE_CONCRETE 10
  - BLUE_CONCRETE_POWDER 10
  - BLUE_GLAZED_TERRACOTTA 10
  - BLUE_ICE 10
  - BLUE_ORCHID 10
  - BLUE_SHULKER_BOX 10
  - BLUE_STAINED_GLASS 10
  - BLUE_STAINED_GLASS_PANE 10
  - BLUE_TERRACOTTA 10
  - BLUE_WALL_BANNER 10
  - BLUE_WOOL 10
  - BONE_BLOCK 10
  - BOOKSHELF 10
  - BRAIN_CORAL 10
  - BRAIN_CORAL_BLOCK 10
  - BRAIN_CORAL_FAN 10
  - BRAIN_CORAL_WALL_FAN 10
  - BREWING_STAND 10
  - BRICKS 10
  - BRICK_SLAB 10
  - BRICK_STAIRS 10
  - BRICK_WALL 10
  - BROWN_BANNER 10
  - BROWN_BED 10
  - BROWN_CARPET 10
  - BROWN_CONCRETE 10
  - BROWN_CONCRETE_POWDER 10
  - BROWN_GLAZED_TERRACOTTA 10
  - BROWN_MUSHROOM 10
  - BROWN_MUSHROOM_BLOCK 10
  - BROWN_SHULKER_BOX 10
  - BROWN_STAINED_GLASS 10
  - BROWN_STAINED_GLASS_PANE 10
  - BROWN_TERRACOTTA 10
  - BROWN_WALL_BANNER 10
  - BROWN_WOOL 10
  - BUBBLE_COLUMN 10
  - BUBBLE_CORAL 10
  - BUBBLE_CORAL_BLOCK 10
  - BUBBLE_CORAL_FAN 10
  - BUBBLE_CORAL_WALL_FAN 10
  - CACTUS 10
  - CAKE 10
  - CAMPFIRE 10
  - CARROTS 10
  - CARTOGRAPHY_TABLE 10
  - CARVED_PUMPKIN 10
  - CAULDRON 10
  - CAVE_AIR 10
  - CHAIN 10
  - CHAIN_COMMAND_BLOCK 10
  - CHEST 10
  - CHIPPED_ANVIL 10
  - CHISELED_NETHER_BRICKS 10
  - CHISELED_POLISHED_BLACKSTONE 10
  - CHISELED_QUARTZ_BLOCK 10
  - CHISELED_RED_SANDSTONE 10
  - CHISELED_SANDSTONE 10
  - CHISELED_STONE_BRICKS 10
  - CHORUS_FLOWER 10
  - CHORUS_PLANT 10
  - CLAY 10
  - COAL_BLOCK 10
  - COAL_ORE 10
  - COARSE_DIRT 10
  - COBBLESTONE 10
  - COBBLESTONE_SLAB 10
  - COBBLESTONE_STAIRS 10
  - COBBLESTONE_WALL 10
  - COBWEB 10
  - COCOA 10
  - COMMAND_BLOCK 10
  - COMPARATOR 10
  - COMPOSTER 10
  - CONDUIT 10
  - CORNFLOWER 10
  - CRACKED_NETHER_BRICKS 10
  - CRACKED_POLISHED_BLACKSTONE_BRICKS 10
  - CRACKED_STONE_BRICKS 10
  - CRAFTING_TABLE 10
  - CREEPER_HEAD 10
  - CREEPER_WALL_HEAD 10
  - CRIMSON_BUTTON 10
  - CRIMSON_DOOR 10
  - CRIMSON_FENCE 10
  - CRIMSON_FENCE_GATE 10
  - CRIMSON_FUNGUS 10
  - CRIMSON_HYPHAE 10
  - CRIMSON_NYLIUM 10
  - CRIMSON_PLANKS 10
  - CRIMSON_PRESSURE_PLATE 10
  - CRIMSON_ROOTS 10
  - CRIMSON_SIGN 10
  - CRIMSON_SLAB 10
  - CRIMSON_STAIRS 10
  - CRIMSON_STEM 10
  - CRIMSON_TRAPDOOR 10
  - CRIMSON_WALL_SIGN 10
  - CRYING_OBSIDIAN 10
  - CUT_RED_SANDSTONE 10
  - CUT_RED_SANDSTONE_SLAB 10
  - CUT_SANDSTONE 10
  - CUT_SANDSTONE_SLAB 10
  - CYAN_BANNER 10
  - CYAN_BED 10
  - CYAN_CARPET 10
  - CYAN_CONCRETE 10
  - CYAN_CONCRETE_POWDER 10
  - CYAN_GLAZED_TERRACOTTA 10
  - CYAN_SHULKER_BOX 10
  - CYAN_STAINED_GLASS 10
  - CYAN_STAINED_GLASS_PANE 10
  - CYAN_TERRACOTTA 10
  - CYAN_WALL_BANNER 10
  - CYAN_WOOL 10
  - DAMAGED_ANVIL 10
  - DANDELION 10
  - DARK_OAK_BUTTON 10
  - DARK_OAK_DOOR 10
  - DARK_OAK_FENCE 10
  - DARK_OAK_FENCE_GATE 10
  - DARK_OAK_LEAVES 10
  - DARK_OAK_LOG 10
  - DARK_OAK_PLANKS 10
  - DARK_OAK_PRESSURE_PLATE 10
  - DARK_OAK_SAPLING 10
  - DARK_OAK_SIGN 10
  - DARK_OAK_SLAB 10
  - DARK_OAK_STAIRS 10
  - DARK_OAK_TRAPDOOR 10
  - DARK_OAK_WALL_SIGN 10
  - DARK_OAK_WOOD 10
  - DARK_PRISMARINE 10
  - DARK_PRISMARINE_SLAB 10
  - DARK_PRISMARINE_STAIRS 10
  - DAYLIGHT_DETECTOR 10
  - DEAD_BRAIN_CORAL 10
  - DEAD_BRAIN_CORAL_BLOCK 10
  - DEAD_BRAIN_CORAL_FAN 10
  - DEAD_BRAIN_CORAL_WALL_FAN 10
  - DEAD_BUBBLE_CORAL 10
  - DEAD_BUBBLE_CORAL_BLOCK 10
  - DEAD_BUBBLE_CORAL_FAN 10
  - DEAD_BUBBLE_CORAL_WALL_FAN 10
  - DEAD_BUSH 10
  - DEAD_FIRE_CORAL 10
  - DEAD_FIRE_CORAL_BLOCK 10
  - DEAD_FIRE_CORAL_FAN 10
  - DEAD_FIRE_CORAL_WALL_FAN 10
  - DEAD_HORN_CORAL 10
  - DEAD_HORN_CORAL_BLOCK 10
  - DEAD_HORN_CORAL_FAN 10
  - DEAD_HORN_CORAL_WALL_FAN 10
  - DEAD_TUBE_CORAL 10
  - DEAD_TUBE_CORAL_BLOCK 10
  - DEAD_TUBE_CORAL_FAN 10
  - DEAD_TUBE_CORAL_WALL_FAN 10
  - DETECTOR_RAIL 10
  - DIAMOND_BLOCK 10
  - DIAMOND_ORE 10
  - DIORITE 10
  - DIORITE_SLAB 10
  - DIORITE_STAIRS 10
  - DIORITE_WALL 10
  - DIRT 10
  - DISPENSER 10
  - DRAGON_EGG 10
  - DRAGON_HEAD 10
  - DRAGON_WALL_HEAD 10
  - DRIED_KELP_BLOCK 10
  - DROPPER 10
  - EMERALD_BLOCK 10
  - EMERALD_ORE 10
  - ENCHANTING_TABLE 10
  - ENDER_CHEST 10
  - END_GATEWAY 10
  - END_PORTAL 10
  - END_PORTAL_FRAME 10
  - END_ROD 10
  - END_STONE 10
  - END_STONE_BRICKS 10
  - END_STONE_BRICK_SLAB 10
  - END_STONE_BRICK_STAIRS 10
  - END_STONE_BRICK_WALL 10
  - FARMLAND 10
  - FERN 0
  - FIRE 0
  - FIRE_CORAL 10
  - FIRE_CORAL_BLOCK 10
  - FIRE_CORAL_FAN 10
  - FIRE_CORAL_WALL_FAN 10
  - FLETCHING_TABLE 10
  - FLOWER_POT 10
  - FROSTED_ICE 10
  - FURNACE 10
  - GILDED_BLACKSTONE 10
  - GLASS 10
  - GLASS_PANE 10
  - GLOWSTONE 10
  - GOLD_BLOCK 10
  - GOLD_ORE 10
  - GRANITE 10
  - GRANITE_SLAB 10
  - GRANITE_STAIRS 10
  - GRANITE_WALL 10
  - GRASS 10
  - GRASS_BLOCK 10
  - GRASS_PATH 10
  - GRAVEL 10
  - GRAY_BANNER 10
  - GRAY_BED 10
  - GRAY_CARPET 10
  - GRAY_CONCRETE 10
  - GRAY_CONCRETE_POWDER 10
  - GRAY_GLAZED_TERRACOTTA 10
  - GRAY_SHULKER_BOX 10
  - GRAY_STAINED_GLASS 10
  - GRAY_STAINED_GLASS_PANE 10
  - GRAY_TERRACOTTA 10
  - GRAY_WALL_BANNER 10
  - GRAY_WOOL 10
  - GREEN_BANNER 10
  - GREEN_BED 10
  - GREEN_CARPET 10
  - GREEN_CONCRETE 10
  - GREEN_CONCRETE_POWDER 10
  - GREEN_GLAZED_TERRACOTTA 10
  - GREEN_SHULKER_BOX 10
  - GREEN_STAINED_GLASS 10
  - GREEN_STAINED_GLASS_PANE 10
  - GREEN_TERRACOTTA 10
  - GREEN_WALL_BANNER 10
  - GREEN_WOOL 10
  - GRINDSTONE 10
  - HAY_BLOCK 10
  - HEAVY_WEIGHTED_PRESSURE_PLATE 10
  - HONEYCOMB_BLOCK 10
  - HONEY_BLOCK 10
  - HOPPER 10
  - HORN_CORAL 10
  - HORN_CORAL_BLOCK 10
  - HORN_CORAL_FAN 10
  - HORN_CORAL_WALL_FAN 10
  - ICE 10
  - INFESTED_CHISELED_STONE_BRICKS 10
  - INFESTED_COBBLESTONE 10
  - INFESTED_CRACKED_STONE_BRICKS 10
  - INFESTED_MOSSY_STONE_BRICKS 10
  - INFESTED_STONE 10
  - INFESTED_STONE_BRICKS 10
  - IRON_BARS 10
  - IRON_BLOCK 10
  - IRON_DOOR 10
  - IRON_ORE 10
  - IRON_TRAPDOOR 10
  - JACK_O_LANTERN 10
  - JIGSAW 10
  - JUKEBOX 10
  - JUNGLE_BUTTON 10
  - JUNGLE_DOOR 10
  - JUNGLE_FENCE 10
  - JUNGLE_FENCE_GATE 10
  - JUNGLE_LEAVES 10
  - JUNGLE_LOG 10
  - JUNGLE_PLANKS 10
  - JUNGLE_PRESSURE_PLATE 10
  - JUNGLE_SAPLING 10
  - JUNGLE_SIGN 10
  - JUNGLE_SLAB 10
  - JUNGLE_STAIRS 10
  - JUNGLE_TRAPDOOR 10
  - JUNGLE_WALL_SIGN 10
  - JUNGLE_WOOD 10
  - KELP 10
  - KELP_PLANT 10
  - LADDER 10
  - LANTERN 10
  - LAPIS_BLOCK 10
  - LAPIS_ORE 10
  - LARGE_FERN 10
  - LAVA 0
  - LECTERN 10
  - LEVER 10
  - LIGHT_BLUE_BANNER 10
  - LIGHT_BLUE_BED 10
  - LIGHT_BLUE_CARPET 10
  - LIGHT_BLUE_CONCRETE 10
  - LIGHT_BLUE_CONCRETE_POWDER 10
  - LIGHT_BLUE_GLAZED_TERRACOTTA 10
  - LIGHT_BLUE_SHULKER_BOX 10
  - LIGHT_BLUE_STAINED_GLASS 10
  - LIGHT_BLUE_STAINED_GLASS_PANE 10
  - LIGHT_BLUE_TERRACOTTA 10
  - LIGHT_BLUE_WALL_BANNER 10
  - LIGHT_BLUE_WOOL 10
  - LIGHT_GRAY_BANNER 10
  - LIGHT_GRAY_BED 10
  - LIGHT_GRAY_CARPET 10
  - LIGHT_GRAY_CONCRETE 10
  - LIGHT_GRAY_CONCRETE_POWDER 10
  - LIGHT_GRAY_GLAZED_TERRACOTTA 10
  - LIGHT_GRAY_SHULKER_BOX 10
  - LIGHT_GRAY_STAINED_GLASS 10
  - LIGHT_GRAY_STAINED_GLASS_PANE 10
  - LIGHT_GRAY_TERRACOTTA 10
  - LIGHT_GRAY_WALL_BANNER 10
  - LIGHT_GRAY_WOOL 10
  - LIGHT_WEIGHTED_PRESSURE_PLATE 10
  - LILAC 10
  - LILY_OF_THE_VALLEY 10
  - LILY_PAD 10
  - LIME_BANNER 10
  - LIME_BED 10
  - LIME_CARPET 10
  - LIME_CONCRETE 10
  - LIME_CONCRETE_POWDER 10
  - LIME_GLAZED_TERRACOTTA 10
  - LIME_SHULKER_BOX 10
  - LIME_STAINED_GLASS 10
  - LIME_STAINED_GLASS_PANE 10
  - LIME_TERRACOTTA 10
  - LIME_WALL_BANNER 10
  - LIME_WOOL 10
  - LODESTONE 10
  - LOOM 10
  - MAGENTA_BANNER 10
  - MAGENTA_BED 10
  - MAGENTA_CARPET 10
  - MAGENTA_CONCRETE 10
  - MAGENTA_CONCRETE_POWDER 10
  - MAGENTA_GLAZED_TERRACOTTA 10
  - MAGENTA_SHULKER_BOX 10
  - MAGENTA_STAINED_GLASS 10
  - MAGENTA_STAINED_GLASS_PANE 10
  - MAGENTA_TERRACOTTA 10
  - MAGENTA_WALL_BANNER 10
  - MAGENTA_WOOL 10
  - MAGMA_BLOCK 10
  - MELON 10
  - MELON_STEM 10
  - MOSSY_COBBLESTONE 10
  - MOSSY_COBBLESTONE_SLAB 10
  - MOSSY_COBBLESTONE_STAIRS 10
  - MOSSY_COBBLESTONE_WALL 10
  - MOSSY_STONE_BRICKS 10
  - MOSSY_STONE_BRICK_SLAB 10
  - MOSSY_STONE_BRICK_STAIRS 10
  - MOSSY_STONE_BRICK_WALL 10
  - MOVING_PISTON 10
  - MUSHROOM_STEM 10
  - MYCELIUM 10
  - NETHERITE_BLOCK 10
  - NETHERRACK 10
  - NETHER_BRICKS 10
  - NETHER_BRICK_FENCE 10
  - NETHER_BRICK_SLAB 10
  - NETHER_BRICK_STAIRS 10
  - NETHER_BRICK_WALL 10
  - NETHER_GOLD_ORE 10
  - NETHER_PORTAL 10
  - NETHER_QUARTZ_ORE 10
  - NETHER_SPROUTS 10
  - NETHER_WART 10
  - NETHER_WART_BLOCK 10
  - NOTE_BLOCK 10
  - OAK_BUTTON 10
  - OAK_DOOR 10
  - OAK_FENCE 10
  - OAK_FENCE_GATE 10
  - OAK_LEAVES 10
  - OAK_LOG 10
  - OAK_PLANKS 10
  - OAK_PRESSURE_PLATE 10
  - OAK_SAPLING 10
  - OAK_SIGN 10
  - OAK_SLAB 10
  - OAK_STAIRS 10
  - OAK_TRAPDOOR 10
  - OAK_WALL_SIGN 10
  - OAK_WOOD 10
  - OBSERVER 10
  - OBSIDIAN 10
  - ORANGE_BANNER 10
  - ORANGE_BED 10
  - ORANGE_CARPET 10
  - ORANGE_CONCRETE 10
  - ORANGE_CONCRETE_POWDER 10
  - ORANGE_GLAZED_TERRACOTTA 10
  - ORANGE_SHULKER_BOX 10
  - ORANGE_STAINED_GLASS 10
  - ORANGE_STAINED_GLASS_PANE 10
  - ORANGE_TERRACOTTA 10
  - ORANGE_TULIP 10
  - ORANGE_WALL_BANNER 10
  - ORANGE_WOOL 10
  - OXEYE_DAISY 10
  - PACKED_ICE 10
  - PEONY 10
  - PETRIFIED_OAK_SLAB 10
  - PINK_BANNER 10
  - PINK_BED 10
  - PINK_CARPET 10
  - PINK_CONCRETE 10
  - PINK_CONCRETE_POWDER 10
  - PINK_GLAZED_TERRACOTTA 10
  - PINK_SHULKER_BOX 10
  - PINK_STAINED_GLASS 10
  - PINK_STAINED_GLASS_PANE 10
  - PINK_TERRACOTTA 10
  - PINK_TULIP 10
  - PINK_WALL_BANNER 10
  - PINK_WOOL 10
  - PISTON 10
  - PISTON_HEAD 10
  - PLAYER_HEAD 10
  - PLAYER_WALL_HEAD 10
  - PODZOL 10
  - POLISHED_ANDESITE 10
  - POLISHED_ANDESITE_SLAB 10
  - POLISHED_ANDESITE_STAIRS 10
  - POLISHED_BASALT 10
  - POLISHED_BLACKSTONE 10
  - POLISHED_BLACKSTONE_BRICKS 10
  - POLISHED_BLACKSTONE_BRICK_SLAB 10
  - POLISHED_BLACKSTONE_BRICK_STAIRS 10
  - POLISHED_BLACKSTONE_BRICK_WALL 10
  - POLISHED_BLACKSTONE_BUTTON 10
  - POLISHED_BLACKSTONE_PRESSURE_PLATE 10
  - POLISHED_BLACKSTONE_SLAB 10
  - POLISHED_BLACKSTONE_STAIRS 10
  - POLISHED_BLACKSTONE_WALL 10
  - POLISHED_DIORITE 10
  - POLISHED_DIORITE_SLAB 10
  - POLISHED_DIORITE_STAIRS 10
  - POLISHED_GRANITE 10
  - POLISHED_GRANITE_SLAB 10
  - POLISHED_GRANITE_STAIRS 10
  - POPPY 10
  - POTATOES 10
  - POTTED_ACACIA_SAPLING 10
  - POTTED_ALLIUM 10
  - POTTED_AZURE_BLUET 10
  - POTTED_BAMBOO 10
  - POTTED_BIRCH_SAPLING 10
  - POTTED_BLUE_ORCHID 10
  - POTTED_BROWN_MUSHROOM 10
  - POTTED_CACTUS 10
  - POTTED_CORNFLOWER 10
  - POTTED_CRIMSON_FUNGUS 10
  - POTTED_CRIMSON_ROOTS 10
  - POTTED_DANDELION 10
  - POTTED_DARK_OAK_SAPLING 10
  - POTTED_DEAD_BUSH 10
  - POTTED_FERN 10
  - POTTED_JUNGLE_SAPLING 10
  - POTTED_LILY_OF_THE_VALLEY 10
  - POTTED_OAK_SAPLING 10
  - POTTED_ORANGE_TULIP 10
  - POTTED_OXEYE_DAISY 10
  - POTTED_PINK_TULIP 10
  - POTTED_POPPY 10
  - POTTED_RED_MUSHROOM 10
  - POTTED_RED_TULIP 10
  - POTTED_SPRUCE_SAPLING 10
  - POTTED_WARPED_FUNGUS 10
  - POTTED_WARPED_ROOTS 10
  - POTTED_WHITE_TULIP 10
  - POTTED_WITHER_ROSE 10
  - POWERED_RAIL 10
  - PRISMARINE 10
  - PRISMARINE_BRICKS 10
  - PRISMARINE_BRICK_SLAB 10
  - PRISMARINE_BRICK_STAIRS 10
  - PRISMARINE_SLAB 10
  - PRISMARINE_STAIRS 10
  - PRISMARINE_WALL 10
  - PUMPKIN 10
  - PUMPKIN_STEM 10
  - PURPLE_BANNER 10
  - PURPLE_BED 10
  - PURPLE_CARPET 10
  - PURPLE_CONCRETE 10
  - PURPLE_CONCRETE_POWDER 10
  - PURPLE_GLAZED_TERRACOTTA 10
  - PURPLE_SHULKER_BOX 10
  - PURPLE_STAINED_GLASS 10
  - PURPLE_STAINED_GLASS_PANE 10
  - PURPLE_TERRACOTTA 10
  - PURPLE_WALL_BANNER 10
  - PURPLE_WOOL 10
  - PURPUR_BLOCK 10
  - PURPUR_PILLAR 10
  - PURPUR_SLAB 10
  - PURPUR_STAIRS 10
  - QUARTZ_BLOCK 10
  - QUARTZ_BRICKS 10
  - QUARTZ_PILLAR 10
  - QUARTZ_SLAB 10
  - QUARTZ_STAIRS 10
  - RAIL 10
  - REDSTONE_BLOCK 10
  - REDSTONE_LAMP 10
  - REDSTONE_ORE 10
  - REDSTONE_TORCH 10
  - REDSTONE_WALL_TORCH 10
  - REDSTONE_WIRE 10
  - RED_BANNER 10
  - RED_BED 10
  - RED_CARPET 10
  - RED_CONCRETE 10
  - RED_CONCRETE_POWDER 10
  - RED_GLAZED_TERRACOTTA 10
  - RED_MUSHROOM 10
  - RED_MUSHROOM_BLOCK 10
  - RED_NETHER_BRICKS 10
  - RED_NETHER_BRICK_SLAB 10
  - RED_NETHER_BRICK_STAIRS 10
  - RED_NETHER_BRICK_WALL 10
  - RED_SAND 10
  - RED_SANDSTONE 10
  - RED_SANDSTONE_SLAB 10
  - RED_SANDSTONE_STAIRS 10
  - RED_SANDSTONE_WALL 10
  - RED_SHULKER_BOX 10
  - RED_STAINED_GLASS 10
  - RED_STAINED_GLASS_PANE 10
  - RED_TERRACOTTA 10
  - RED_TULIP 10
  - RED_WALL_BANNER 10
  - RED_WOOL 10
  - REPEATER 10
  - REPEATING_COMMAND_BLOCK 10
  - RESPAWN_ANCHOR 10
  - ROSE_BUSH 10
  - SAND 10
  - SANDSTONE 10
  - SANDSTONE_SLAB 10
  - SANDSTONE_STAIRS 10
  - SANDSTONE_WALL 10
  - SCAFFOLDING 10
  - SEAGRASS 10
  - SEA_LANTERN 10
  - SEA_PICKLE 10
  - SHROOMLIGHT 10
  - SHULKER_BOX 10
  - SKELETON_SKULL 10
  - SKELETON_WALL_SKULL 10
  - SLIME_BLOCK 10
  - SMITHING_TABLE 10
  - SMOKER 10
  - SMOOTH_QUARTZ 10
  - SMOOTH_QUARTZ_SLAB 10
  - SMOOTH_QUARTZ_STAIRS 10
  - SMOOTH_RED_SANDSTONE 10
  - SMOOTH_RED_SANDSTONE_SLAB 10
  - SMOOTH_RED_SANDSTONE_STAIRS 10
  - SMOOTH_SANDSTONE 10
  - SMOOTH_SANDSTONE_SLAB 10
  - SMOOTH_SANDSTONE_STAIRS 10
  - SMOOTH_STONE 10
  - SMOOTH_STONE_SLAB 10
  - SNOW 10
  - SNOW_BLOCK 10
  - SOUL_CAMPFIRE 10
  - SOUL_FIRE 10
  - SOUL_LANTERN 10
  - SOUL_SAND 10
  - SOUL_SOIL 10
  - SOUL_TORCH 10
  - SOUL_WALL_TORCH 10
  - SPAWNER 10
  - SPONGE 10
  - SPRUCE_BUTTON 10
  - SPRUCE_DOOR 10
  - SPRUCE_FENCE 10
  - SPRUCE_FENCE_GATE 10
  - SPRUCE_LEAVES 10
  - SPRUCE_LOG 10
  - SPRUCE_PLANKS 10
  - SPRUCE_PRESSURE_PLATE 10
  - SPRUCE_SAPLING 10
  - SPRUCE_SIGN 10
  - SPRUCE_SLAB 10
  - SPRUCE_STAIRS 10
  - SPRUCE_TRAPDOOR 10
  - SPRUCE_WALL_SIGN 10
  - SPRUCE_WOOD 10
  - STICKY_PISTON 10
  - STONE 10
  - STONECUTTER 10
  - STONE_BRICKS 10
  - STONE_BRICK_SLAB 10
  - STONE_BRICK_STAIRS 10
  - STONE_BRICK_WALL 10
  - STONE_BUTTON 10
  - STONE_PRESSURE_PLATE 10
  - STONE_SLAB 10
  - STONE_STAIRS 10
  - STRIPPED_ACACIA_LOG 10
  - STRIPPED_ACACIA_WOOD 10
  - STRIPPED_BIRCH_LOG 10
  - STRIPPED_BIRCH_WOOD 10
  - STRIPPED_CRIMSON_HYPHAE 10
  - STRIPPED_CRIMSON_STEM 10
  - STRIPPED_DARK_OAK_LOG 10
  - STRIPPED_DARK_OAK_WOOD 10
  - STRIPPED_JUNGLE_LOG 10
  - STRIPPED_JUNGLE_WOOD 10
  - STRIPPED_OAK_LOG 10
  - STRIPPED_OAK_WOOD 10
  - STRIPPED_SPRUCE_LOG 10
  - STRIPPED_SPRUCE_WOOD 10
  - STRIPPED_WARPED_HYPHAE 10
  - STRIPPED_WARPED_STEM 10
  - STRUCTURE_BLOCK 10
  - STRUCTURE_VOID 10
  - SUGAR_CANE 10
  - SUNFLOWER 10
  - SWEET_BERRY_BUSH 10
  - TALL_GRASS 10
  - TALL_SEAGRASS 10
  - TARGET 10
  - TERRACOTTA 10
  - TNT 10
  - TORCH 10
  - TRAPPED_CHEST 10
  - TRIPWIRE 10
  - TRIPWIRE_HOOK 10
  - TUBE_CORAL 10
  - TUBE_CORAL_BLOCK 10
  - TUBE_CORAL_FAN 10
  - TUBE_CORAL_WALL_FAN 10
  - TURTLE_EGG 10
  - TWISTING_VINES 10
  - TWISTING_VINES_PLANT 10
  - VINE 10
  - VOID_AIR 10
  - WALL_TORCH 10
  - WARPED_BUTTON 10
  - WARPED_DOOR 10
  - WARPED_FENCE 10
  - WARPED_FENCE_GATE 10
  - WARPED_FUNGUS 10
  - WARPED_HYPHAE 10
  - WARPED_NYLIUM 10
  - WARPED_PLANKS 10
  - WARPED_PRESSURE_PLATE 10
  - WARPED_ROOTS 10
  - WARPED_SIGN 10
  - WARPED_SLAB 10
  - WARPED_STAIRS 10
  - WARPED_STEM 10
  - WARPED_TRAPDOOR 10
  - WARPED_WALL_SIGN 10
  - WARPED_WART_BLOCK 10
  - WATER 0
  - WEEPING_VINES 10
  - WEEPING_VINES_PLANT 10
  - WET_SPONGE 10
  - WHEAT 10
  - WHITE_BANNER 10
  - WHITE_BED 10
  - WHITE_CARPET 10
  - WHITE_CONCRETE 10
  - WHITE_CONCRETE_POWDER 10
  - WHITE_GLAZED_TERRACOTTA 10
  - WHITE_SHULKER_BOX 10
  - WHITE_STAINED_GLASS 10
  - WHITE_STAINED_GLASS_PANE 10
  - WHITE_TERRACOTTA 10
  - WHITE_TULIP 10
  - WHITE_WALL_BANNER 10
  - WHITE_WOOL 10
  - WITHER_ROSE 10
  - WITHER_SKELETON_SKULL 10
  - WITHER_SKELETON_WALL_SKULL 10
  - YELLOW_BANNER 10
  - YELLOW_BED 10
  - YELLOW_CARPET 10
  - YELLOW_CONCRETE 10
  - YELLOW_CONCRETE_POWDER 10
  - YELLOW_GLAZED_TERRACOTTA 10
  - YELLOW_SHULKER_BOX 10
  - YELLOW_STAINED_GLASS 10
  - YELLOW_STAINED_GLASS_PANE 10
  - YELLOW_TERRACOTTA 10
  - YELLOW_WALL_BANNER 10
  - YELLOW_WOOL 10
  - ZOMBIE_HEAD 10
  - ZOMBIE_WALL_HEAD 10